// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLXPsgB_JJ1HdPXFeA8GnK2ILuzTnPnzE',
    appId: '1:597624233095:android:257fdc4775deb11fa06c22',
    messagingSenderId: '597624233095',
    projectId: 'civams-face',
    storageBucket: 'civams-face.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEl3lE_a_GRs10a-TFD8Vg10LG_rGZ58A',
    appId: '1:597624233095:ios:7324eaed8d34d037a06c22',
    messagingSenderId: '597624233095',
    projectId: 'civams-face',
    storageBucket: 'civams-face.appspot.com',
    androidClientId: '597624233095-1kk53plbblag3ippc7lq3riv5k1gshk9.apps.googleusercontent.com',
    iosClientId: '597624233095-sb2ui09odavcnmpior8belm17c8l5lar.apps.googleusercontent.com',
    iosBundleId: 'ngmduc2012.com.baseApp',
  );
}
